### ISSUE TITLE
The sv-restaurant website got a design update so probably the scraper needs to be changed...

### ISSUE THREAD

**Issue by mirioeggmann** [jmesserli/svmeal-api#11]
Because "https://svmeal-api.jmnw.me/api/restaurant/bit/meal/0" returns an error page. :stuck_out_tongue_winking_eye:

**Comment by jmesserli** [comment]
Thanks for the report, I already noticed it this morning when I tried to
access our meals of the day :(

Sadly they changed the page structure quite a bit but I'll make sure to fix
this in the evening.

**Comment by mirioeggmann** [comment]
yeah same haha & true they completely changed the page structure, so no hurry :v:
