### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by rainerduffner** [jmesserli/svmeal-api#24]
Hi,

due to reorganizations of the web-site, it seems the code does not work anymore.

Unfortunately, people are still hammering the website with it.

The code should have had measures in place to prevent this IMO.

**Comment by jmesserli** [comment]
Hi. Currently, the SV website itself is returning an error 500 for the restaurant search endpoint:
![image](https://user-images.githubusercontent.com/613138/95726031-af349600-0c78-11eb-9a7a-17547c73c1da.png)
(it doesn't work on the SV page either).

I do agree that the server should not be hammered when it's malfunctioning. I'll look into using a circuit breaker.

**Comment by rainerduffner** [comment]
```
IP1 - - [12/Oct/2020:10:58:49 +0200] "POST /de/mitarbeiterrestaurants/restaurant-suche/?type=8700 HTTP/1.1" 404 56496 "-" "sv-meal/2 github.com/jmesserli/svmeal-api"
IP1 - - [12/Oct/2020:10:58:52 +0200] "POST /de/mitarbeiterrestaurants/restaurant-suche/?type=8700 HTTP/1.1" 404 56504 "-" "sv-meal/2 github.com/jmesserli/svmeal-api"
IP2 - - [12/Oct/2020:10:58:56 +0200] "POST /de/mitarbeiterrestaurants/restaurant-suche/?type=8700 HTTP/1.1" 301 178 "-" "sv-meal/2 github.com/jmesserli/svmeal-api"
IP1 - - [12/Oct/2020:10:59:09 +0200] "POST /de/mitarbeiterrestaurants/restaurant-suche/?type=8700 HTTP/1.1" 404 56504 "-" "sv-meal/2 github.com/jmesserli/svmeal-api"
IP1 - - [12/Oct/2020:10:59:12 +0200] "POST /de/mitarbeiterrestaurants/restaurant-suche/?type=8700 HTTP/1.1" 404 56496 "-" "sv-meal/2 github.com/jmesserli/svmeal-api"
IP1 - - [12/Oct/2020:10:59:29 +0200] "POST /de/mitarbeiterrestaurants/restaurant-suche/?type=8700 HTTP/1.1" 404 56504 "-" "sv-meal/2 github.com/jmesserli/svmeal-api"
IP1 - - [12/Oct/2020:10:59:32 +0200] "POST /de/mitarbeiterrestaurants/restaurant-suche/?type=8700 HTTP/1.1" 404 56544 "-" "sv-meal/2 github.com/jmesserli/svmeal-api"

```

I've complained to their ISPs. Maybe I should just ban them...

**Comment by jmesserli** [comment]
I've taken my instance down for now. That would have been 37.120.166.80 - I hope it wasn't me.

**Comment by rainerduffner** [comment]
You were IP2....

IP1 is still active.

**Comment by jmesserli** [comment]
Sorry about that.

I'm currently implementing the circuit breaker, and it seems to be working so far.
![image](https://user-images.githubusercontent.com/613138/95731383-c0cd6c00-0c7f-11eb-8c71-9bf0754afbc5.png)

I currently have it configured to break open after 10 failed calls, after which it will not do any calls for 5 minutes.
Does that sound sensible to you?

**Comment by jmesserli** [comment]
I've pushed a fix including the circuit breaker.

And I've also contacted someone that I think is also running the software on their end. Hopefully, they can integrate the fix soon.

**Comment by rainerduffner** [comment]
The hammering seems to have stopped, thank you.

**Comment by jmesserli** [comment]
I'm closing this issue for now. If future problems arise, feel free to open an issue again.
